### ISSUE TITLE
Markdown bold/italic/underline incorrect

### ISSUE THREAD

**Issue by scrooks** [jheddings/notional#185]
Notional Version: 0.8.0

### Description ###

Bold/italic/underline are incorrect in the markdown generator.

This happens in text.py `__string__()`, which should look like this:

```python
        if self.annotations:
            if self.annotations.bold:
                text = f"**{text}**"
            if self.annotations.italic:
                text = f"*{text}*"
            if self.annotations.underline:
                text = f"<u>{text}</u>"
            if self.annotations.strikethrough:
                text = f"~{text}~"
            if self.annotations.code:
                text = f"`{text}`"
```

Apologies for not doing a pull request.

**Comment by jheddings** [comment]
Oops!  Not sure how I mixed those two up...  I've opened a PR and will get this fixed in the next release.

**Comment by scrooks** [comment]
We’ve all mixed things up plenty, I’m sure.
