### ISSUE TITLE
if self.filter is not None, create a compound for both filters

### ISSUE THREAD

**Issue by SandNerd** [jheddings/notional#20]
Sorry, this issue was created with VSCode Github extension. Super convenient but didn't give me a chance to explain!

Exactly as you guessed. I was running multiple filters and getting more results with each filter! Then found out in your code it was basically taking the last one.

Great library by the way. It's just missing a number of features to make it the de facto Notion ORM.

**Comment by jheddings** [comment]
Can you provide more context where you are seeing the error?  I imagine you are using the Query Builder to append multiple filters, but would like clarification.  Thanks!

**Comment by SandNerd** [comment]
Edited

**Comment by jheddings** [comment]
I believe I have a fix that will work for you...  I had to change a few of the object interfaces (including serialization of `CompoundFilter`).  If you have time, would you mind installing from the repo and letting me know if that is the behavior you were expecting?  Thanks!
