### ISSUE TITLE
MultiSelect property not updating on Notion when using .remove

### ISSUE THREAD

**Issue by iAmNikola** [jheddings/notional#30]
**Describe the bug**
Removing an option from MultiSelect using .remove on a MultiSelect ORM property doesn't update the property on Notion 

**To Reproduce**

1. Have a ORM class
2. Get an instance of the ORM that has a multi select property whether by creating it or pulling it from Notion
3. Use .remove on the property
4. See that it didn't update on Notion

**Expected behavior**
When using types.MultiSelect.remove() I expect for it to update on Notion as well.

**Additional context**
My current workaround is just doing something like this:
```python
class DatasetPage(CustomPage):
    multi: types.MultiSelect = Property("Multi", types.MultiSelect)
    def remove_tag(self, tag_to_remove):
        self.multi = self.multi.remove(tag_to_remove)

```

Thanks for the great work!

**Comment by jheddings** [comment]
Thanks for the write up!

This is a valid issue and applies to the other types as well...  Specifically, we need a better way to determine if the property is being modified as a local object or a connected type.

Have you tried using the in-place removal method to see if that will work?  e.g.

```python
class DatasetPage(CustomPage):
    multi: types.MultiSelect = Property("Multi", types.MultiSelect)

page = DatasetPage(...)
page.multi -= tag_to_remove
```

That should modify the value in place as a property of the `DatesetPage` type and update Notion.

**Comment by iAmNikola** [comment]
Sorry for the late response.

I have tried using your solution and I can verify it works as intended.
Thanks!

As for further development on this topic. I think most people would want local changes to be applied to the notion page as soon as possible, but that's just my two cents :)

Can't wait to see what this project has in store. Keep up the great work!
