### ISSUE TITLE
Can't filter a database by FormulaCondition: a TextCondition property type.

### ISSUE THREAD

**Issue by victorterancas** [jheddings/notional#51]
### Description ###

FormulaCondition options weren't correct defined.

### Steps To Reproduce ###

1. Go to 'https://github.com/jheddings/notional/blob/1efc5eb66b341b191f2954de43bdfe60440fe16d/notional/query.py#L141'
2. `text` should be changed by `string`.

### Expected Behavior ###

Filter a database by FormulaCondition: a TextCondition property type.

### Screenshots ###

![image](https://user-images.githubusercontent.com/92316283/170480712-e5940fa8-0ea7-4855-8b03-346627ed4d52.png)

Doesn't match the official API client:
![image](https://user-images.githubusercontent.com/92316283/170480640-a6f0e6f3-8e2a-4f14-b7ff-a8307f74c0c7.png)

The code should be:
![image](https://user-images.githubusercontent.com/92316283/170481105-2941fa7c-dab4-49db-a4d2-1d1724bf84c0.png)

**Comment by jheddings** [comment]
Thanks for the bug report!  There have been several field changes that were not released in the API change log...  I'll make this change quickly and scan for others.
