### ISSUE TITLE
Filtering for search endpoint

### ISSUE THREAD

**Issue by FlorianWilhelm** [jheddings/notional#57]
### Description ###

As far as I know, the [filtering capabilities for the search endpoint ](https://developers.notion.com/reference/post-search) are right now not implemented. For instance, I would have expected that in order to search only for databases with name `DB Name` I could write:
```
notion.search("DB Name").filter(property="object", value="database")
```
but that doesn't seem to work. 

### Proposed Solution ###

Implement this as a new FilterType.

**Comment by jheddings** [comment]
Good catch...  It looks like the filter object for search is different than other queries (which I obviously didn't test well enough).  It should be pretty straightforward to make this change.  Hopefully I can get to it soon.
