### ISSUE TITLE
Unable to set Select properties when the color has been set.

### ISSUE THREAD

**Issue by jheddings** [jheddings/notional#69]
Notional Version: 0.4.3

### Description ###

Cannot set the value of a Select property to an existing value when the color has been set.  The following error occurs:

```
notion_client.errors.APIResponseError: Select option color doesn't match existing
```

### Steps To Reproduce ###

Using the ORM interface, attempt to set the value of a `Select` property to an existing value.

### Additional Context ###

The default color in the `SelectOne` compose interface is `Color.DEFAULT` when it should be `None`.

**Comment by mimansajaiswal** [comment]
There is a similar error when trying to set a status property to an existing value (even in the latest version)

**Comment by jheddings** [comment]
Whoops!  😳 

You are right, the same problem happens on status properties.  I'm pushing a fix now and will publish an updated package shortly.
